# sops.yaml
creation_rules:
  - gcp_kms: projects/ica1-1234/locations/northamerica-northeast2/keyRings/my-keyring/cryptoKeys/my-key
    # Specify any file patterns you want to auto-encrypt
    path_regex: '.*\.yaml$'
    encrypted_regex: '^(data)$'

